services:
  yt-downloader:
    build:
      context: ./yt_downloader
      dockerfile: Dockerfile
    container_name: yt_downloader
    volumes:
      - ./data:/data
    environment:
      MAX_PER_DAY: 5
      DELAY_HOURS: 4
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    environment:
      # These can also come from your .env file
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
            
    volumes:
      - ./data:/srv
      - ./web-editor/database:/database
      - ./web-editor/config:/config
    restart: unless-stopped